apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-training
data:
  NODE_ENV: "production"
  APP_PORT: "3000"
  DB_HOST: "postgres-svc"
  DB_PORT: "5432"
  DB_NAME: "appdb"
  LOG_LEVEL: "info"