apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: prod-
namespace: devops-prod
patches:
  - path: replicas-patch.yaml
images:
  - name: ghcr.io/atu0601/devops-app
    newTag: 1.0.0