apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-app-dev
  namespace: argocd
spec:
  project: devops-training
  source:
    repoURL: https://github.com/atu0601/devops-gitops.git
    targetRevision: main
    path: gitops/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m